// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.shephertz.app42.paas;

import com.shephertz.app42.paas.App42User;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect App42User_Roo_Configurable {
    
    declare @type: App42User: @Configurable;
    
}
